channels:
  - rdkit
  - pytorch
dependencies:
  - python=3.7
  - anaconda
  - rdkit
  - pytorch=1.4
  - torchvision
  - cudatoolkit=10.1
  - pandas
  - seaborn
  - scikit-learn
  - pyarrow
  - numba
  - click
  - pip
  - pip:
    - python-igraph
    - ruffus
    - tqdm
    - networkx
    - tensorboardX
    - cirpy    
    - pubchempy
    - ruamel.yaml
    
