exp_data:
  filename : '../nmrdata/processed_data/nmrshiftdb_64_64_HCONFSPCl_1H.shifts.dataset.pickle'
  extra_data : []

net_name: nets.GraphVertModelMaskedBN

net_params:
  init_noise : 0.0 
  resnet : True 
  int_d :  2048 
  layer_n : 10 
  GS : 4 
  agg_func : goodmax 
  force_lin_init : True 
  g_feature_n : -1 
  resnet_out : True 
  out_std : True
  batchnorm :  False
  input_batchnorm : True 
  graph_dropout : 0.0 
  resnet_blocks : [3,]
  resnet_d: 128
  out_std_exp : False 
  OUT_DIM : 1 # update

batch_size: 16

tgt_max_n: 64 

spectra_nucs : ['1H']

opt_params:
  optimizer : adam 
  lr : 1.0e-5
  scheduler_gamma : 0.95 
  eps : 1.0e-8 
  scheduler_step_size : 100
  
    
seed : 1234

dataset_hparams:
  use_default: True
  feat_vect_args:
    mmff_atom_types_onehot : True
    feat_atomicno: False


loss_params:
  loss_name : NormUncertainLoss
  mu_scale: [0.05]
  std_scale : [10.0]
  std_regularize: 0.01

max_epochs: 4000
